- name: loops ansible playbook
  hosts: localhost
  become: yes
  tasks:
  - name: install multiple packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
      ignore_erros: true
    loop:
    - nginx
    - nfs
    - git
    - mysql
    - vallu andharu