- name: loops ansible playbook
  hosts: localhost
  become: yes
  tasks:
  - name: install or uninstall packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
      ignore_erros: true
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'nginx', state: 'absent'}
    - {name: 'java', state: 'absent'}