- name: variables using in ansible playbook
  hosts: localhost
  vars:
    name: "KIraN"
    course: "anni courses'S"
    duration: "100 days"
  tasks:
  - name: check variables
    vars:
      course: "em Courses levvu ra"
    ansible.builtin.debug:
      msg: "Hello {{name}}, I am learning {{course}} from today till {{duration}}"