- name: variables using in ansible playbook
  hosts: localhost
  vars_files: 
    variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hello {{name}}, I am learning {{course}} from today till {{duration}}"