- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter me namakaranam
    course: DAWS
    prompt: Me course ento enter cheyandi ra
    duration: just today 
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hello {{name}}, I am learning {{course}} from today till {{duration}}" 