- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter me namakaranam
    private: false
    name: PASSWORD
  - prompt: password thagalapettandi ikkada
    private: true
  tasks:
  - name: print prompt variables
    ansible.builtin.debug:
      msg: "Hello name {{USERNAME}}, and password id {{PASSWORD}} "